<?php
# This file was automatically generated by the MediaWiki 1.46.0-alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "TableWiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://localhost:8081";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/images/logo.png",
	'icon' => "$wgResourceBasePath/images/logo.png",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "db";
$wgDBname = "mediawiki";
$wgDBuser = "wiki";
$wgDBpassword = "wiki";

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];
$wgObjectCaches = [
	CACHE_ACCEL => [ 'class' => 'APCUBagOStuff' ],
	CACHE_DB => [ 'class' => 'SqlBagOStuff' ],
	CACHE_ANYTHING => [ 'factory' => 'ObjectCache::newAnything' ],
	'redis' => [
		'class' => 'RedisBagOStuff',
		'servers' => [ 'redis:6379' ],
	],
];
$wgSessionCacheType = 'redis';
$wgMessageCacheType = 'redis';
$wgParserCacheType = 'redis';

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
$wgCacheDirectory = "$IP/cache";

## Performance optimizations
# Temporarily disabled to debug encoding issues
$wgUseFileCache = false;
$wgFileCacheDirectory = "$IP/cache";
$wgUseLocalMessageCache = false;
$wgEnableSidebarCache = false;
$wgUseGzip = false;

## Additional performance settings
$wgUseETag = true;
# Temporarily disabled to debug encoding issues
$wgDisableOutputCompression = true;
$wgResourceLoaderMaxQueryLength = 2000;
$wgResourceLoaderStorageVersion = 3;
$wgMiserMode = false;
$wgDisableCounters = true;
$wgHitCounterUpdateFreq = 1;
$wgShowIPinHeader = false;
$wgDBserver = "db";
$wgDBprefix = "";
$wgDBssl = false;
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";
$wgSharedTables[] = "actor";

## Job queue optimization
$wgJobRunRate = 1;
$wgJobTypeConf['default'] = [
	'class' => 'JobQueueRedis',
	'redisServer' => 'redis',
	'redisConfig' => [
		'password' => null,
	],
];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/Languages/Data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

$wgSecretKey = "0a8e4ad169d0dcb38e94e11f1e2eeb9df4b262100c831f7f2ad05e9a6197eedb";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "c00b23272ab468c4";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector-2022";

# Enabled skins.
wfLoadSkin( 'Vector' );
wfLoadSkin( 'MonoBook' );

# End of automatically generated settings.
# Add more configuration options below.

# Require login to edit.
$wgGroupPermissions['*']['edit'] = false;

# Allow per-page language settings (needed for Chinese source pages on an English wiki).
$wgPageLanguageUseDB = true;
$wgGroupPermissions['sysop']['pagelang'] = true;

# Language selector and page translation.
# Temporarily disabled to avoid conflict with LanguageBarFooter
# wfLoadExtension( 'UniversalLanguageSelector' );
# $wgULSPosition = 'personal';

# wfLoadExtension( 'Translate' );
# $wgGroupPermissions['user']['translate'] = true;
# $wgGroupPermissions['user']['translate-messagereview'] = true;
# $wgGroupPermissions['sysop']['pagetranslation'] = true;
# $wgEnablePageTranslation = true;
# $wgTranslatePageTranslationULS = true;
# $wgPageTranslationLanguageList = 'tag-only';

# Review workflow (FlaggedRevs)
wfLoadExtension( 'FlaggedRevs' );
$wgFlaggedRevsNamespaces = [ NS_MAIN ];
$wgFlaggedRevsAutoReview = 0;
$wgFlaggedRevsOverride = true;

# Language Bar Footer Extension
wfLoadExtension( 'LanguageBarFooter' );
